### PR TITLE
Count installed snaps and flatpaks

### PR DESCRIPTION
**Pull request by alpheratz0**
resolves this issue #42

### CODE REVIEW

**Review by 0n1cOn3 — APPROVED** [review]
@Mangeshrex Looks Good. Wdym?

**Comment by Mangeshrex** [comment]
I don't have flatpak and snap @0n1cOn3 did you test the script ?

**Comment by 0n1cOn3** [comment]
Yup. And not yet. Arrive home in 5min. Can test then (or via SSH im dumbo lol)

**Comment by Mangeshrex** [comment]
Lel whatever test it and assure me then I'll merge it xD

**Comment by 0n1cOn3** [comment]
Give u a ping in Telegram :)

**Comment by alpheratz0** [comment]
rxfetch
Tested on Pop!_OS

**Comment by Mangeshrex** [comment]
👍👍

**Comment by alpheratz0** [comment]
@Mangeshrex can you close #42?

**Pull request merged**
