### PR TITLE
Add de/wm field?

### PR DESCRIPTION
**Pull request by Animeshz**
Green color was missing, so why not add it 😁?

Dunno why but the light (cyan) color look more consistent than red in uptime :p
Maybe revert that back to cyan 🤔🤔??

### CODE REVIEW

**Comment by Mangeshrex** [comment]
Sorry for the late reply. Can you also keep the red color to some other type like init or something else.

**Comment by Animeshz** [comment]
Hn, It'll look good if we put init between ker & pkgs with red, and ram above disk I'd guess, lemme try.

**Comment by Mangeshrex** [comment]
yes lemme know when you have push all the changes ill merge it

**Comment by Animeshz** [comment]
How about this 
image

**Comment by Animeshz** [comment]
image
Or this

```bash
echo "               "
echo -e "               ${c1}os${c3}     ${distro} $(uname -m)"
echo -e "               ${c2}ker${c3}    $(uname -r)"
echo -e "     ${c3}•${c8}_${c3}•${c0}       ${c5}init${c3}   $(get_init)"
echo -e "     ${c8}${c0}${c9}oo${c0}${c8}|${c0}       ${c4}pkgs${c3}   $(net_pkg)"
echo -e "    ${c8}/${c0}${c10} ${c0}${c8}'\'${c0}      ${c7}sh${c3}     $(basename "${SHELL}")"
echo -e "   ${c9}(${c0}${c8}\_;/${c0}${c9})${c0}      ${c1}de/wm${c3}  $(get_de_wm)"
echo -e "               ${c5}up${c3}    $(uptime -p | sed 's/up//')"
echo -e "               ${c2}ram${c3}    $(get_mem)"
echo -e "               ${c4}disk${c3}   $storageused / $storageavail"
echo -e "               "
echo -e "        ${c6}󰮯  ${c6}${c2}󰊠  ${c2}${c4}󰊠  ${c4}${c5}󰊠  ${c5}${c7}󰊠  ${c7}"
echo -e "               \033[0m"
```

This one has some pattern over the colors, look more pleasant to eyes :))

**Comment by Mangeshrex** [comment]
yeah better now merging

**Comment by Animeshz** [comment]
Hey didn't did any changes 🤔 I just asked for review bro 😅😅

**Comment by Animeshz** [comment]
Expected to have this in that part 😅😅, can't reopen/push

```bash
echo "               "
echo -e "               ${c1}os${c3}     ${distro} $(uname -m)"
echo -e "               ${c2}ker${c3}    $(uname -r)"
echo -e "     ${c3}•${c8}_${c3}•${c0}       ${c5}init${c3}   $(get_init)"
echo -e "     ${c8}${c0}${c9}oo${c0}${c8}|${c0}       ${c4}pkgs${c3}   $(net_pkg)"
echo -e "    ${c8}/${c0}${c10} ${c0}${c8}'\'${c0}      ${c6}sh${c3}     $(basename "${SHELL}")"
echo -e "   ${c9}(${c0}${c8}\_;/${c0}${c9})${c0}      ${c1}de/wm${c3}  $(get_de_wm)"
echo -e "               ${c5}up${c3}    $(uptime -p | sed 's/up//')"
echo -e "               ${c2}ram${c3}    $(get_mem)"
echo -e "               ${c4}disk${c3}   $storageused / $storageavail"
echo -e "               "
echo -e "        ${c6}󰮯  ${c6}${c2}󰊠  ${c2}${c4}󰊠  ${c4}${c5}󰊠  ${c5}${c7}󰊠  ${c7}"
echo -e "               \033[0m"
```

**Comment by Mangeshrex** [comment]
Idk what changes you have made here. can you explain ?

**Comment by Animeshz** [comment]
@Mangeshrex Merged changes contain de/wm field as in first image at the very top, I asked for review of different colors below bit didn't changed anything (color) in the pr 👀👀

**Pull request merged**
